package sep.project.repositories;

import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import sep.project.model.Merchant;

/**
* Generated by Spring Data Generator on 20/12/2019
*/
@Repository
public interface MerchantRepository extends JpaRepository<Merchant, Long>, JpaSpecificationExecutor<Merchant> {

	Optional<Merchant> findByEmail(String email);
}
