package sep.project.repositories;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import sep.project.model.Transaction;

/**
* Generated by Spring Data Generator on 20/12/2019
*/
@Repository
public interface TransactionRepository extends JpaRepository<Transaction, Long>, JpaSpecificationExecutor<Transaction> {

	@Query("SELECT t FROM Transaction t WHERE t.status = ?1 or t.status = ?2 or t.status = ?3")
	public List<Transaction> getTransactionWithStatuses(String status1, String status2, String status3);
}
