package sep.project.repositories;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import sep.project.model.Transaction;
import sep.project.model.TransactionStatus;

/**
* Generated by Spring Data Generator on 20/12/2019
*/
@Repository
public interface TransactionRepository extends JpaRepository<Transaction, Long>, JpaSpecificationExecutor<Transaction> {

	@Query("SELECT t FROM Transaction t WHERE t.status = ?1 or t.status = ?2 or t.status = ?3")
	public List<Transaction> getTransactionWithStatuses(TransactionStatus status1, TransactionStatus status2, TransactionStatus status3);
	
	public Transaction findByPaymentId(Long paymentId);
	
	public Transaction findByOrderId(Long orderId);
	
	@Query("SELECT distinct trans FROM Transaction trans inner join trans.merchant as m WHERE trans.orderId = ?1 and m.email = ?2 ")
	public Transaction findMerchantTransactionBasedOnId(Long id, String email);
}
