package sep.project.enums;

public enum Status {
	// CREATED, WAITING, SUCCESSFULLY, UNSUCCESSFULLY,EXPIRED
	CREATED, WAITING, SUCCESSFULLY, UNSUCCESSFULLY, WAITING_PCC, UNSUCCESSFULLY_KP, SUCCESSFULLY_KP, CREATED_KP,
	UNSUCCESSFULLY_PCC, SUCCESSFULLY_PCC, EXPIRED_KP, EXPIRED
}
